name: Bug report
description: File a bug report
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: E.g. "the bonus button isn't claimed"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: E.g. go to a streamer page and then click on another streamer
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: E.g. the bonus points should be claimed
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) can you reproduce the issue on?
      multiple: true
      options:
      - Chrome
      - Firefox
      - Chromium Edge
      - Opera
      - Vivaldi
      - Brave
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What OS does it occur on?
      options:
      - Windows
      - macOS
      - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What's the version you're running?
      description: Go to the extensions page and copy the version number
    validations:
      required: true
  - type: checkboxes
    id: reported
    attributes:
      label: Make sure the bug wasn't reported before
      options:
      - label: I'm the first one to [report](https://github.com/avi12/twitch-cp-bonus-collector/issues?q=is%3Aissue) it
        required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
